### ISSUE TITLE
Segfault YAML::detail::node_data::is_defined

### ISSUE THREAD

**Issue by manfredmann** [jbeder/yaml-cpp#1022]
Sorry for my bad english.

ymal-cpp version 0.6.3
g++ 11.1.0

File: 

```
> cat config.yml -n
   1 video:
   2   filter: 3
   3   brigtness: 0
   4   contrast: 0
   5   hue: 0
   6   saturation: 0
   7   unlim_sprites: false
   8 input:
   9   player0:
  10     btn_right: 65
  11     btn_left: 68
  12     btn_down: 83
  13     btn_up: 87
  14     btn_start: 16777220
  15     btn_b: 16777234
  16     btn_a: 16777237
  17     btn_select: 16777248
```

Code:
```
#include <iostream>
#include <yaml-cpp/yaml.h>

int main(int argc, char *argv[]) {
    YAML::Node node = YAML::LoadFile("config.yml");
    try {
        const YAML::Node &          input = node["input"];
        for (YAML::const_iterator i = input.begin(); i != input.end(); ++i) {
            const YAML::Node &      buttons_cfg = i->second;

            for (YAML::const_iterator j = buttons_cfg.begin(); j != buttons_cfg.end(); ++j) {
                // segfault on last iteration

                if (!j->first.IsScalar()) {
                    continue;
                }

                std::cout << j->first.as<std::string>() << std::endl;
            }
        }
   } catch (const YAML::Exception &e) {
       std::cout << "error: " << e.what() << ", line: " << e.mark.line << " column: " << e.mark.column << std::endl;
   }

    return 0;
}

```

Output:
```
> g++ main.cpp -lyaml-cpp -o test
> ./test 
btn_right
btn_left
btn_down
btn_up
btn_start
btn_b
btn_a
btn_select
fish: Job 1, './test' terminated by signal SIGSEGV (Address boundary error)
```

gdb bt
```
Program received signal SIGSEGV, Segmentation fault.
0x000055555555c0ec in std::__shared_ptr<YAML::detail::node_data, (__gnu_cxx::_Lock_policy)2>::get() const ()
(gdb) bt
#0  0x000055555555c0ec in std::__shared_ptr<YAML::detail::node_data, (__gnu_cxx::_Lock_policy)2>::get() const ()
#1  0x000055555555b56e in std::__shared_ptr_access<YAML::detail::node_data, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const ()
#2  0x000055555555a9de in std::__shared_ptr_access<YAML::detail::node_data, (__gnu_cxx::_Lock_policy)2, false, false>::operator->() const ()
#3  0x00005555555596bc in YAML::detail::node_ref::is_defined() const ()
#4  0x0000555555559914 in YAML::detail::node::is_defined() const ()
#5  0x000055555555d353 in YAML::detail::node_iterator_base<YAML::detail::node>::is_defined(__gnu_cxx::__normal_iterator<std::pair<YAML::detail::node*, YAML::detail::node*>*, std::vector<std::pair<YAML::detail::node*, YAML::detail::node*>, std::allocator<std::pair<YAML::detail::node*, YAML::detail::node*> > > >) const ()
#6  0x000055555555c8c2 in YAML::detail::node_iterator_base<YAML::detail::node>::increment_until_defined(__gnu_cxx::__normal_iterator<std::pair<YAML::detail::node*, YAML::detail::node*>*, std::vector<std::pair<YAML::detail::node*, YAML::detail::node*>, std::allocator<std::pair<YAML::detail::node*, YAML::detail::node*> > > >) ()
#7  0x000055555555bc07 in YAML::detail::node_iterator_base<YAML::detail::node>::operator++() ()
#8  0x000055555555b110 in YAML::detail::iterator_base<YAML::detail::iterator_value const>::operator++() ()
#9  0x000055555555870e in main ()

```
If i remove type checking, i'm getting exception:

Code 

```
#include <iostream>
#include <yaml-cpp/yaml.h>

int main(int argc, char *argv[]) {
    YAML::Node node = YAML::LoadFile("config.yml");
    try {
        const YAML::Node &          input = node["input"];
        for (YAML::const_iterator i = input.begin(); i != input.end(); ++i) {
            const YAML::Node &      buttons_cfg = i->second;

            for (YAML::const_iterator j = buttons_cfg.begin(); j != buttons_cfg.end(); ++j) {
                // segfault on last iteration

                // if (!j->first.IsScalar()) {
                //     continue;
                // }

                std::cout << j->first.as<std::string>() << std::endl;
            }
        }
   } catch (const YAML::Exception &e) {
       std::cout << "error: " << e.what() << ", line: " << e.mark.line << " column: " << e.mark.column << std::endl;
   }

    return 0;
}
```

Output:

```
> g++ main.cpp -lyaml-cpp -o test
> ./test
btn_right
btn_left
btn_down
btn_up
btn_start
btn_b
btn_a
btn_select
error: bad conversion, line: -1 column: -1
```
What am I doing wrong?

**Comment by lingxd** [comment]
same quesution
