### ISSUE TITLE
AddressSanitizer reports stack-use-after-scope

### ISSUE THREAD

**Issue by Liam0205** [jbeder/yaml-cpp#977]
## Environment

* CentOS 7
* yaml-cpp 0.6
* LLVM clang++ 8.0.1

## MWE

```yaml demo.yaml
hello:
  - world
hi:
  - world
```

```cpp mwe.cc
#include <yaml-cpp/yaml.h>

#include <iostream>

int main() {
  YAML::Node config = YAML::LoadFile("./demo.yaml");
  for (auto iter = config.begin(); iter != config.end(); ++iter) {
    auto& list = iter->second;
    const size_t sz = list.size();
    std::cout << list << std::endl;
  }
  return 0;
}
```

When build with `-fsanitize=address,bounds`, binary aborts with the following error message:

```
=================================================================
==218037==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd0b1c90b0 at pc 0x000000501b4f bp 0x7ffd0b1c8df0 sp 0x7ffd0b1c8de8
READ of size 1 at 0x7ffd0b1c90b0 thread T0                                                                          
    #0 0x501b4e in YAML::Node::size() const /tmp/third_party/yaml-cpp-0.6/include/yaml-cpp/node/impl.h:278:8        
    #1 0x501b4e in main /tmp/sandbox/liam/mwe/yaml-cpp-stack-use-after-scope/mwe.cc:9                                                                                                                                         
    #2 0x7fae5aff2554 in __libc_start_main (/lib64/libc.so.6+0x22554)
    #3 0x422408 in _start (/home/liam/svn/ks/.build/diag_opt/targets/sandbox/liam/mwe/yaml-cpp-stack-use-after-scope/yaml-cpp-stack-use-after-scope+0x422408)

Address 0x7ffd0b1c90b0 is located in stack of thread T0 at offset 688 in frame
    #0 0x5000df in main /tmp/sandbox/liam/mwe/yaml-cpp-stack-use-after-scope/mwe.cc:5

  This frame has 10 object(s):
    [32, 40) 'ref.tmp.i172'
    [64, 76) 'ref.tmp.i164'
    [96, 120) 'ref.tmp2.i'
    [160, 256) 'ref.tmp.i'
    [288, 320) 'agg.tmp.i40'
    [352, 384) 'agg.tmp.i'
    [416, 448) 'config' (line 6)
    [480, 504) 'ref.tmp' (line 6)
    [544, 592) 'iter' (line 7)
    [624, 720) 'ref.tmp8' (line 8) <== Memory access at offset 688 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /tmp/third_party/yaml-cpp-0.6/include/yaml-cpp/node/impl.h:278:8 in YAML::Node::size() const
Shadow bytes around the buggy address:
  0x1000216311c0: f1 f1 f1 f1 f8 f2 f2 f2 f8 f8 f2 f2 f8 f8 f8 f2
  0x1000216311d0: f2 f2 f2 f2 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x1000216311e0: f2 f2 f2 f2 f8 f8 f8 f8 f2 f2 f2 f2 f8 f8 f8 f8
  0x1000216311f0: f2 f2 f2 f2 00 00 00 00 f2 f2 f2 f2 f8 f8 f8 f2
  0x100021631200: f2 f2 f2 f2 00 00 00 00 00 00 f2 f2 f2 f2 f8 f8
=>0x100021631210: f8 f8 f8 f8 f8 f8[f8]f8 f8 f8 f3 f3 f3 f3 f3 f3
  0x100021631220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021631230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021631240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021631250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100021631260: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==218037==ABORTING
```

**Comment by Liam0205** [comment]
Related posts:

* <https://stackoverflow.com/questions/65357508/c-reference-inconsistency?noredirect=1&lq=1>

**Comment by Liam0205** [comment]
Well, after diving into source of the project, it seems to be a bug of iterator.

When calling member access operator of iterator, it constructs a temporary object of `proxy`. See:
https://github.com/jbeder/yaml-cpp/blob/98acc5a8874faab28b82c28936f4b400b389f5d6/include/yaml-cpp/node/detail/iterator.h#L87

However, constructing `proxy` makes a copy of the object pointed by the iterator. See the constructor of `proxy`.
https://github.com/jbeder/yaml-cpp/blob/98acc5a8874faab28b82c28936f4b400b389f5d6/include/yaml-cpp/node/detail/iterator.h#L31-L37

This leads to the fact that `auto& list = iter->second;` refers to *the member data of a temporary `proxy` object*. And after the very sentence is executed, the temporary `proxy` object is destroyed. From then on, any use of `list` might cause a `stack-use-after-scope` error.

To fix this, type of the member `m_ref` of the `proxy` struct should be `const V&`.

**Comment by Liam0205** [comment]
Hmmm, it looks like yaml-cpp itself has reference semantics.

Something looks like a copy, internally it works like a C++ reference.

```cpp
auto list = iter->second;
list[0] = "Liam";  // <-- this will actually modify the original list.
```

Something looks like a reference, internally it causes a UB.

```cpp
auto& list = iter->second;
list[0] = "Liam";  // <-- undefined behavior, stack-use-after-scope.
```

Would @jbeder kindly consider to fix this?

**Comment by sunmy2019** [comment]
Everything here is contained in a `Node`. `Node` is designed here to hold the reference, leaving the underneath memory untouched. When dereferencing the iterator, what you get is just another `std::pair<Node, Node>`.

So you`auto& list` binds to a temporary `Node`.

The author chooses not to expose the memory, to prevent possible dangling reference. It happens sometimes. For example in
```cpp
std::vector<int> v{1};
auto &ref1 = v[0];

v.reserve(100); // reallocating the memory, causing ref1 a dangling reference.
```
He decides to give you a `Node` object here, hiding the real location. It is possible to give you a `Node` that lives longer. But whatever you bind or copy, you get something has a reference semantic.

After knowing the behavior of `Node` and iterator returing `std::pair<Node, Node>`, copying this `Node` become quite natural.

**Comment by Liam0205** [comment]
@sunmy2019 

What you've said is does not change the fact that in yaml-cpp, copy works like a reference, but reference results in UB.

**Comment by sunmy2019** [comment]
You shouldn't use reference. The proxy type exists because it needs to return a pointer to the dereference result. Thus making `(*iter).second` behaves alike to the `iter->second`. Otherwise you need to write something like `iter.operator->().second`.
But since the derefence result is not stored in the iterator itself, `sturct proxy` is just a work around. It do cause some confusion. It is hard to return a pointer and decide when to destroy that object. You must choose from a dangling refernce or a memory leak.

Copy works like a reference is a must in the current design. You want a copy of the underlying for `auto` and a `auto&` for reference. That means a directed exposure of memory, also a correct type given.

The current design underneath is to use `shard_ptr` of a validate type `YAML::memory`. The actual type of data cannot be deduced until running. So an `auto/auto&` to copy or bind the real memory is impossible unless you tell it the type. It can be done with some efforts, but it also means a much more complicated interface.

Also the returning of a `Node` ensures you to use his interface to assign, read, output the value, leaving the underneath `YAML::memory` untouched. There could be a dangling reference, if you bind to a memory which is managed by the `shared_ptr`.

So a `Node` is a must for current polymorphism design.

**Comment by Liam0205** [comment]
@sunmy2019 TL;DR.

You do not need to explain to me that why we got UB as a result, 'cause I had already known, before your first reply. What I wonder is that the internal reason behind this weird design.

**Comment by sunmy2019** [comment]
@sunmy2019 
I explained why your idea isn't possible.

**Comment by jrood-nrel** [comment]
I would love to see this fixed since I always have to suppress ASAN/UBSAN warnings from yaml-cpp.

**Comment by themightyoarfish** [comment]
How _do_ I suppress these ASAN errors? I could never get the suppression file to work. Can someone elaborate?

**Comment by themightyoarfish** [comment]
For me I see the error in this code in `Node` impl by the way:
```
inline iterator Node::begin() {
  if (!m_isValid)
    return iterator();
  return m_pNode ? iterator(m_pNode->begin(), m_pMemory) : iterator();
}
```
(version 0.6.2).

Is this not something to be concerned about, considering the issue is a year old?

**Comment by jrood-nrel** [comment]
@themightyoarfish I had to use a blacklist. This is how I do it https://github.com/Exawind/build-test/blob/9332a23324b2b2a98184f3be20a4f22b8db57939/test-scripts/test-nalu-wind.sh#L304

**Comment by WilliamTambellini** [comment]
Apparently still an issue with the current master.

**Comment by themightyoarfish** [comment]
Any update on this?

**Comment by WilliamTambellini** [comment]
Just confirming it still hits:
```
=================================================================
==9231==
ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd6a861280 at pc 0x0000005604c2 bp 0x7ffd6a860770 sp 0x7ffd6a860768
READ of size 1 at 0x7ffd6a861280 thread T0
    #0 0x5604c1 in YAML::Node::Node(YAML::Node const&) include/yaml-cpp/node/impl.h:45
    #1 0x7f42cd09d1db in YAML::convert<YAML::Node>::encode(YAML::Node const&) include/yaml-cpp/node/convert.h:54
    #2 0x7f42cd09d1db in YAML::detail::node& YAML::detail::node_data::convert_to_node<YAML::Node>(YAML::Node const&, std::shared_ptr<YAML::detail::memory_holder>) include/yaml-cpp/node/detail/impl.h:235
    #3 0x7f42cd09d1db in void YAML::detail::node_data::force_insert<std::string, YAML::Node>(std::string const&, YAML::Node const&, std::shared_ptr<YAML::detail::memory_holder>) include/yaml-cpp/node/detail/impl.h:220
    #4 0x7f42cd09d1db in void YAML::detail::node_ref::force_insert<std::string, YAML::Node>(std::string const&, YAML::Node const&, std::shared_ptr<YAML::detail::memory_holder>) include/yaml-cpp/node/detail/node_ref.h:114
    #5 0x7f42cd09d1db in void YAML::detail::node::force_insert<std::string, YAML::Node>(std::string const&, YAML::Node const&, std::shared_ptr<YAML::detail::memory_holder>) include/yaml-cpp/node/detail/node.h:196
    #6 0x7f42cd09d1db in void YAML::Node::force_insert<std::string, YAML::Node>(std::string const&, YAML::Node const&) include/yaml-cpp/node/impl.h:385
```

**Comment by WilliamTambellini** [comment]
@jbeder any comment ?

**Comment by jbeder** [comment]
It looks like the original report deliberately triggered undefined behavior? I guess that would make this not a bug, but rather working as intended.

Maybe the question is, why the library chooses to behave this way? I originally chose reference semantics because it seemed to fit nicely with the way that YAML works (with anchors and aliases, etc.). I'm not certain this was the right decision, but as noted, it would take a lot of work to change this behavior. (Or, really, it would require a new API to avoid breaking existing users.)

I'm happy to review any PRs, but practically speaking, this is unlikely to change, unless someone agrees to take over maintenance of the library.

**Comment by fpf3** [comment]
@jbeder No, the original report iterated over a node in a way that is natural to do, and it caused a stack-use-after-scope to happen. This is most definitely a bug, unless you'd care to share a snippet that does not trigger this behavior.

**Comment by jbeder** [comment]
The problem isn't in the iteration, but rather the line

```
auto& list = iter->second;
```

If you replace it with

```
auto list = iter->second;
```

then the code is not UB.

**Comment by Liam0205** [comment]
Wow, this is quite an old issue, and I almost forgot the exact situation I encountered back then. (laughs)

After a quick glance at the code, if we change the type of the member `m_ref` in the `proxy` struct from `V` to `V&` (that is, change it to an lvalue reference), would that solve the problem? Say, the following 

https://github.com/jbeder/yaml-cpp/blob/98acc5a8874faab28b82c28936f4b400b389f5d6/include/yaml-cpp/node/detail/iterator.h#L31-L37

should be changed to 

```cpp
  struct proxy {
    explicit proxy(const V& x) : m_ref(x) {}
    V* operator->() { return std::addressof(m_ref); }
    operator V*() { return std::addressof(m_ref); }

    V& m_ref;
  };
```

I'm not sure if it would introduce any side effects though.

**Comment by jbeder** [comment]
You wouldn't be able to assign the const ref to a non-const ref in the constructor.

**Comment by Liam0205** [comment]
> You wouldn't be able to assign the const ref to a non-const ref in the constructor.

Oh, yes... I made a silly mistake... Let's just ignore it~

**Comment by jrood-nrel** [comment]
Does 0.8.0 fix this issue?

**Comment by jbeder** [comment]
No, last discussion was that this was a misuse of the library, not a bug.

**Comment by WilliamTambellini** [comment]
seems to be also reported by cve-bin-tool
https://github.com/intel/cve-bin-tool
